### ISSUE TITLE
Restore PG/TimescaleDB

### ISSUE THREAD

**Issue by zN3utr4l** [offen/docker-volume-backup#35]
I'm trying to restore my data in the **TimeScale db, a Postgresql extension**, the backup is performed perfectly, even the restore, I can access the backup data, but when in **django** I try to **migrate** this is the error that comes back to me:

**psycopg2.errors.DataCorrupted: could not read block 4 in file "base/17542/2604": read only 0 of 8192 bytes**

**Inspecting** the block, with this query: `SELECT * FROM pg_class WHERE oid = 2604`, it turns out that it is the **pg_attrdef** block

For the **restore** I tried to use both your recommended commands: [this in github](https://github.com/offen/docker-volume-backup#restoring-a-volume-from-a-backup), and those recommended by docker: [this: docker run --rm --volumes-from timescale -v C:\BackupVolume:/backup ubuntu bash -c "cd /var/lib/postgresql/data/ && tar xvf /backup/last-backup.tar.gz --strip 1"](https://docs.docker.com/storage/volumes/#restore-volume-from-backup) but with both the result is the same.

The mapping with the volume and the data folder is correct, I used [this](https://github.com/jareware/docker-volume-backup) to make backups and it never gave me problems apart from that it used to use 15 GB of Ram for I don't know what reason.

_Traceback:_
```
(facco_env) PS C:\Users\l.logiudice\Analysis Detection\costal.dataanalyser\Analyser> python.exe .\manage.py migrate
AutoDiscover task...
Operations to perform:
Apply all migrations: admin, admin_interface, auth, contenttypes, django_celery_beat, django_celery_results, main, mongodb, rabbitmqservice, sessions, statistic, variables
Running migrations:
Traceback (most recent call last):
File "C:\Users\l.logiudice\miniconda3\envs\facco_env\lib\site-packages\django\db\backends\utils.py", line 82, in _execute
return self.cursor.execute(sql)
psycopg2.errors.DataCorrupted: could not read block 4 in file "base/17542/2604": read only 0 of 8192 bytes




The above exception was the direct cause of the following exception:



Traceback (most recent call last):
File "C:\Users\l.logiudice\miniconda3\envs\facco_env\lib\site-packages\django\db\migrations\recorder.py", line 68, in ensure_schema
editor.create_model(self.Migration)
File "C:\Users\l.logiudice\miniconda3\envs\facco_env\lib\site-packages\django\db\backends\base\schema.py", line 345, in create_model
self.execute(sql, params or None)
File "C:\Users\l.logiudice\miniconda3\envs\facco_env\lib\site-packages\django\db\backends\base\schema.py", line 145, in execute
cursor.execute(sql, params)
File "C:\Users\l.logiudice\miniconda3\envs\facco_env\lib\site-packages\django\db\backends\utils.py", line 98, in execute
return super().execute(sql, params)
File "C:\Users\l.logiudice\miniconda3\envs\facco_env\lib\site-packages\django\db\backends\utils.py", line 66, in execute
return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
File "C:\Users\l.logiudice\miniconda3\envs\facco_env\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
return executor(sql, params, many, context)
File "C:\Users\l.logiudice\miniconda3\envs\facco_env\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
return self.cursor.execute(sql, params)
File "C:\Users\l.logiudice\miniconda3\envs\facco_env\lib\site-packages\django\db\utils.py", line 90, in __exit__
raise dj_exc_value.with_traceback(traceback) from exc_value
File "C:\Users\l.logiudice\miniconda3\envs\facco_env\lib\site-packages\django\db\backends\utils.py", line 82, in _execute
return self.cursor.execute(sql)
django.db.utils.InternalError: could not read block 4 in file "base/17542/2604": read only 0 of 8192 bytes




During handling of the above exception, another exception occurred:



Traceback (most recent call last):
File ".\manage.py", line 23, in <module>
main()
File ".\manage.py", line 19, in main
execute_from_command_line(sys.argv)
File "C:\Users\l.logiudice\miniconda3\envs\facco_env\lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line
utility.execute()
File "C:\Users\l.logiudice\miniconda3\envs\facco_env\lib\site-packages\django\core\management\__init__.py", line 413, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "C:\Users\l.logiudice\miniconda3\envs\facco_env\lib\site-packages\django\core\management\base.py", line 354, in run_from_argv
self.execute(*args, **cmd_options)
File "C:\Users\l.logiudice\miniconda3\envs\facco_env\lib\site-packages\django\core\management\base.py", line 398, in execute
output = self.handle(*args, **options)
File "C:\Users\l.logiudice\miniconda3\envs\facco_env\lib\site-packages\django\core\management\base.py", line 89, in wrapped
res = handle_func(*args, **kwargs)
File "C:\Users\l.logiudice\miniconda3\envs\facco_env\lib\site-packages\django\core\management\commands\migrate.py", line 244, in handle
post_migrate_state = executor.migrate(
File "C:\Users\l.logiudice\miniconda3\envs\facco_env\lib\site-packages\django\db\migrations\executor.py", line 91, in migrate
self.recorder.ensure_schema()
File "C:\Users\l.logiudice\miniconda3\envs\facco_env\lib\site-packages\django\db\migrations\recorder.py", line 70, in ensure_schema
raise MigrationSchemaMissing("Unable to create the django_migrations table (%s)" % exc)
django.db.migrations.exceptions.MigrationSchemaMissing: Unable to create the django_migrations table (could not read block 4 in file "base/17542/2604": read only 0 of 8192 bytes
)
```

**Comment by m90** [comment]
This is close to impossible for me to debug unfortunately as it seems to have a lot of very specific moving parts.

> The DB from which I have to backup is on Linux (Debian 10), while where I have to restore it is Windows 10

Can you do a restore on Linux?

**Comment by zN3utr4l** [comment]
Sorry, both the Timescale DB and the django app are distributed on docker, so both in linux

**Comment by m90** [comment]
In case I am not mistaken, you use `BACKUP_FROM_SNAPSHOT`. Does the issue also persist if you do not use that?

**Comment by zN3utr4l** [comment]
I need to use it because I cannot stop the timescale container, I have already tried not to use it but it gave me errors such as the size did not match
